spring.cloud.stream:
  function:
    definition: streamProcessor
  bindings:
    domainProcessor-in-0:
      destination: KafkaTopic
    domainProcessor-out-0:
      destination: KafkaTopic
  kafka:
    bindings:
      domainProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      domainProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      binder:
        broker:
          -localhost:9091
          -localhost:9092

---

spring.cloud.stream:
  function:
    definition: consumerService
  bindings:
    domainProcessor-out-0:
      destination: KafkaTopic
  kafka:
    bindings:
      domainProcessor-out-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      binder:
        broker:
          -localhost:9091
          -localhost:9092